### ISSUE TITLE
Technical Guideline -- Technical Infrastructure Update (2)

### ISSUE THREAD

**Issue by Joshocan** [cessda/cessda.guidelines.public#106]
The "Continuous Integration" subsection require updates

- 

```[tasklist]
### Tasks
- [x] Platform Process mini-section is out of date
- [x] Deployment Pipeline Overview: Content and diagram require update
- [x] Deployment Workflow: Content and diagram require update
- [x] Deployment Pipeline Detail: Content and diagram require update
- [x] The CESSDA Branching Model for Deployments : Content and diagrams update
- [x] Using Helm to Deploy Products: Update content
- [x] Building Maven Project with Jenkins: Update content
- [x] Building Docker Image in Jenkins : Remove redundancy content
- [x] Building with Docker: Content update
```
