### ISSUE TITLE
Review Technical Guidelines

### ISSUE THREAD

**Issue by Joshocan** [cessda/cessda.guidelines.public#111]
```[tasklist]
### Tasks
- [ ] https://github.com/cessda/cessda.guidelines.public/issues/106
- [ ] https://github.com/cessda/cessda.guidelines.public/issues/105
- [ ] https://github.com/cessda/cessda.guidelines.public/issues/107
- [ ] https://github.com/cessda/cessda.guidelines.public/issues/108
- [ ] https://github.com/cessda/cessda.guidelines.public/issues/109
- [ ] https://github.com/cessda/cessda.guidelines.public/issues/102
- [ ] https://github.com/cessda/cessda.guidelines.public/issues/110
```
